# -*- coding: utf-8 -*-
"""Fake_News_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SYAgQiXCi1t3q4bMrrIJ00lUSFHZxaQ

# AI-Powered Fake News Detection Using Text Classification

### Objective
To build a machine learning model that classifies news articles as Real or Fake using Natural Language Processing (NLP) and Machine Learning techniques.

---
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import re
import string

from sklearn.model_selection import train_test_split

# Display plots in notebook
# %matplotlib inline

"""## Dataset Loading

The fake news dataset was obtained from Kaggle and consists of two separate files:

- **True.csv** – Contains authentic news articles.
- **Fake.csv** – Contains fabricated news articles.

Both datasets were merged into a single dataset and labeled for binary classification.
"""

fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

print("Fake News Dataset Shape :", fake_df.shape)
print("True News Dataset Shape :", true_df.shape)

fake_df.head()

true_df.head()

"""## Data Cleaning

The dataset was inspected for missing values, duplicate records, and inconsistencies.

Cleaning steps performed:
- Merged Fake and True datasets.
- Assigned numerical labels (1 = Real, 0 = Fake).
- Removed duplicate news articles.
- Removed unnecessary columns.
- Prepared the dataset for Natural Language Processing.
"""

fake_df.info()

true_df.info()

print("Missing values in Fake Dataset")
print(fake_df.isnull().sum())

print("\n----------------------\n")

print("Missing values in True Dataset")
print(true_df.isnull().sum())

print("Fake Dataset Duplicates :", fake_df.duplicated().sum())

print("True Dataset Duplicates :", true_df.duplicated().sum())

fake_df["label"] = 0
true_df["label"] = 1

news_df = pd.concat([fake_df, true_df], axis=0)
print("Combined Dataset Shape:", news_df.shape)

news_df.drop_duplicates(inplace=True)
print("Dataset Shape After Removing Duplicates:", news_df.shape)

news_df = news_df.sample(frac=1, random_state=42).reset_index(drop=True)

news_df["label"].value_counts()

news_df.head()

"""## Exploratory Data Analysis

Exploratory Data Analysis (EDA) was performed to understand the dataset.

The following analyses were carried out:
- Class distribution of Real and Fake news.
- Word Clouds for both categories.
- Basic dataset statistics.
"""

news_df["content"] = news_df["title"] + " " + news_df["text"]

news_df["label"].value_counts()

plt.figure(figsize=(6,4))
sns.countplot(x="label", data=news_df)
plt.title("Distribution of Fake and Real News")
plt.xlabel("Label")
plt.ylabel("Count")
plt.xticks([0,1],["Fake","Real"])
plt.savefig("class_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

news_df["text_length"] = news_df["content"].apply(len)

news_df["text_length"].describe()

plt.figure(figsize=(8,5))
sns.histplot(news_df["text_length"], bins=50)
plt.title("Distribution of Article Length")
plt.xlabel("Characters")
plt.ylabel("Frequency")
plt.savefig("article_length_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x="label", y="text_length", data=news_df)
plt.xticks([0,1],["Fake","Real"])
plt.title("Article Length Comparison")
plt.savefig("article_length_boxplot.png", dpi=300, bbox_inches="tight")
plt.show()

"""## Text Preprocessing

Natural Language Processing (NLP) techniques were applied to clean the news articles before training.

The preprocessing pipeline includes:
- Converting text to lowercase.
- Removing punctuation.
- Removing numbers.
- Removing extra spaces.
- Removing stopwords.
- Lemmatization.
"""

import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # Handle missing values
    if pd.isna(text):
        return ""

    # Convert to lowercase
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Tokenization
    words = text.split()

    # Remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

news_df["clean_text"] = news_df["content"].apply(clean_text)

print("Original Text:\n")
print(news_df["content"].iloc[0])
print("\n" + "="*100 + "\n")

print("Cleaned Text:\n")
print(news_df["clean_text"].iloc[0])

"""## Feature Engineering

The cleaned news articles were converted into numerical representations using the TF-IDF (Term Frequency–Inverse Document Frequency) technique.

TF-IDF assigns higher importance to informative words while reducing the influence of commonly occurring words, making it suitable for text classification tasks.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=5,
    max_df=0.7
)

X = tfidf.fit_transform(news_df["clean_text"])

y = news_df["label"]

print("Feature Matrix Shape:", X.shape)
print("Labels Shape:", y.shape)

"""## Train-Test Split

The dataset was divided into training (80%) and testing (20%) sets using stratified sampling to preserve the class distribution in both subsets.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data :", X_train.shape)
print("Testing Data  :", X_test.shape)

"""## Model Training

Four machine learning algorithms were implemented and compared:

- Logistic Regression
- K-Nearest Neighbors (KNN)
- Random Forest
- Neural Network (MLP)

Each model was trained using the same TF-IDF feature vectors to ensure a fair comparison.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

results = []

def evaluate_model(model, model_name):

    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    results.append([
        model_name,
        accuracy,
        precision,
        recall,
        f1
    ])

    print("="*60)
    print(model_name)
    print("="*60)

    print(classification_report(y_test, predictions))

    plt.figure(figsize=(5,4))

    sns.heatmap(
        confusion_matrix(y_test, predictions),
        annot=True,
        fmt="d",
        cmap="Blues"
    )

    plt.title(model_name)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.savefig(f"{model_name}_confusion_matrix.png", dpi=300, bbox_inches="tight")

    plt.show()

"""## Model Evaluation

Each model was evaluated using the following performance metrics:

- Accuracy
- Precision
- Recall
- F1-Score
- Confusion Matrix

The models were compared to determine the most effective classifier for fake news detection.
"""

lr=LogisticRegression()
evaluate_model(lr, "Logistic Regression")

knn = KNeighborsClassifier(n_neighbors=5)

evaluate_model(knn, "KNN")

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

evaluate_model(rf, "Random Forest")

mlp = MLPClassifier(
    hidden_layer_sizes=(100,),
    max_iter=300,
    random_state=42
)

evaluate_model(mlp, "Neural Network")

results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

results_df.sort_values(
    by="Accuracy",
    ascending=False
)

"""## Saving the Best Model

The best-performing model and the TF-IDF vectorizer were saved using Joblib. This allows the trained model to be reused for future predictions without retraining.
"""

import joblib

joblib.dump(rf, "fake_news_random_forest.pkl")

joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")

"""## Prediction on Custom News

A prediction function was developed to classify unseen news articles as either **Real News** or **Fake News** using the saved machine learning model.
"""

def predict_news(news):

    cleaned = clean_text(news)

    vector = tfidf.transform([cleaned])

    prediction = rf.predict(vector)[0]

    probability = rf.predict_proba(vector)[0]

    if prediction == 0:
        print("Prediction : FAKE NEWS")
    else:
        print("Prediction : REAL NEWS")

    print()

    print(f"Confidence : {max(probability)*100:.2f}%")

predict_news("""
NASA announces successful landing of astronauts on the Moon after a six-month mission.
""")

predict_news("""
Government secretly confirms aliens are controlling all world leaders through invisible satellites.
""")

sample_news = input("Enter a news article: ")

predict_news(sample_news)

"""## Visualization & Analysis"""

plt.figure(figsize=(8,5))

bars = plt.bar(results_df["Model"], results_df["Accuracy"])

plt.title("Accuracy Comparison of Machine Learning Models")
plt.xlabel("Models")
plt.ylabel("Accuracy")

plt.ylim(0.6, 1.01)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{height:.4f}",
        ha='center',
        va='bottom',
        fontsize=10
    )
plt.savefig("model_accuracy_comparison.png", dpi=300, bbox_inches="tight")

plt.show()

from wordcloud import WordCloud

fake_words = " ".join(news_df[news_df["label"] == 0]["clean_text"])

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color="white"
).generate(fake_words)

plt.figure(figsize=(14,7))
plt.imshow(wordcloud)
plt.axis("off")
plt.title("Most Frequent Words in Fake News")
plt.savefig("fake_news_wordcloud.png", dpi=300, bbox_inches="tight")
plt.show()

real_words = " ".join(news_df[news_df["label"] == 1]["clean_text"])

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color="white"
).generate(real_words)

plt.figure(figsize=(14,7))
plt.imshow(wordcloud)
plt.axis("off")
plt.title("Most Frequent Words in Real News")
plt.savefig("real_news_wordcloud.png", dpi=300, bbox_inches="tight")
plt.show()

"""## Feature Importance"""

feature_names = tfidf.get_feature_names_out()

importances = rf.feature_importances_

feature_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
})

top_features = feature_df.sort_values(
    by="Importance",
    ascending=False
).head(20)

top_features

plt.figure(figsize=(10,7))

plt.barh(
    top_features["Feature"],
    top_features["Importance"]
)

plt.title("Top 20 Important Features")

plt.xlabel("Importance")

plt.gca().invert_yaxis()
plt.savefig("feature_importance.png", dpi=300, bbox_inches="tight")
plt.show()

"""## Conclusion

A complete machine learning pipeline for fake news detection was successfully developed using Natural Language Processing techniques.

The project demonstrates how machine learning can effectively identify misinformation based on textual patterns. Among the evaluated models, the best-performing classifier was selected for deployment.

Future enhancements may include using transformer-based language models such as BERT, integrating live news APIs for real-time analysis, and deploying the application using Streamlit or Flask.

## Dataset Acknowledgement

**Dataset Source:** Kaggle – Real & Fake News Dataset

**License:** CC BY-NC-SA 4.0

This dataset is used strictly for educational and non-commercial purposes in accordance with its license. Proper attribution will also be provided in the project report and presentation.
"""